spring:
  jpa:
    hibernate:
      ddl-auto: 'update'
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/shops
    username: root
    password: 12345
  flyway:
    baseline-on-migrate: true